[project]
name = "fmix"
version = "0.1.0"
description = "🎧 A scripted track mixer 🎧"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "tdir>=1.9.0",
    "tomlkit>=0.14.0",
    "tuney",
    "tyro>=1.0.12",
]

[tool.uv]
package = true

[tool.ruff.format]
quote-style = "single"

[tool.uv.sources]
tuney = { path = "../tuney", editable = true }

[dependency-groups]
dev = [
    "coverage>=7.13.5",
    "pytest>=9.0.2",
    "pyupgrade>=3.21.2",
    "ruff>=0.15.9",
    "soundfile>=0.13.1",
    "tdir>=1.9.0",
    "tomlkit>=0.14.0",
    "ty>=0.0.28",
]

[project.scripts]
fmix = "fmix.__main__:main"

[tool.poetry]
name = "fmix"
version = "0.1.0"
description = "🎧 A scripted track mixer 🎧"
authors = ["Tom Ritchford <tom@swirly.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.13"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
